// MongoDB "DDL" create the indexes in the "olympics" database
// and its collections.
//
// Generated on: 2021-10-26 19:28:58 UTC
// Generated by: artifact_generator.py gen_target_cosmos_mongo_indexes()
// Template:     mongo_database_indexes.ddl
// TODO:         the customer needs to manually edit the this file

use olympics

// db.games.ensureIndex({"some_attribute" : 1}, {"unique" : false})

// db.locations.ensureIndex({"some_attribute" : 1}, {"unique" : false})


show collections