// MongoDB "DDL" create the indexes in the "{{ dbname }}" database
// and its collections.
//
// Generated on: {{ gen_timestamp }}
// Generated by: {{ gen_by }}
// Template:     mongo_database_indexes.ddl
// TODO:         the customer needs to manually edit the this file

use {{ dbname }}

{% for c in collections -%}
// db.{{ c }}.ensureIndex({"some_attribute" : 1}, {"unique" : false})

{% endfor %}
show collections