#!/bin/bash

# Bash shell script to invoke Azure Data Factory with the az CLI
# to execute pipeline 'pipeline_copy_to_olympics_games'. 
#
# Generated on:  2021-10-26 19:28:58 UTC
# Generated by:  artifact_generator.py gen_adf_az_pipeline_scripts()
# Template:      adf_az_cli.txt

source env.sh

az datafactory pipeline create-run \
    --factory-name $M2C_ADF_NAME \
    --resource-group $M2C_RG \
    --parameters "{}" \
    --name pipeline_copy_to_olympics_games

echo 'done'