#!/bin/bash

# Bash shell script to create, the list, the blob containers for this migration.
#
# Generated on: 2021-10-26 19:28:58 UTC
# Generated by: artifact_generator.py gen_python_create_containers()
# Template:     create_blob_containers.txt

source env.sh

python storage.py create_blob_container olympics-games-adf
python storage.py create_blob_container olympics-locations-adf
python storage.py create_blob_container olympics-raw
python storage.py create_blob_container openflights-raw
python storage.py create_blob_container travel-airlines-adf
python storage.py create_blob_container travel-airports-adf
python storage.py create_blob_container travel-countries-adf
python storage.py create_blob_container travel-planes-adf
python storage.py create_blob_container travel-routes-adf


python storage.py list_blob_containers

echo 'done'