#!/bin/bash

# bash script to execute the mongo command-line program, redirecting
# in a "ddl" file to indexes for your collections in the Cosmos/Mongo database.
# TODO: the customer needs to manually edit the input ddl file with the indexes.
#
# Generated on: 2021-10-26 19:28:58 UTC
# Generated by: artifact_generator.py gen_target_cosmos_mongo_indexes()
# Template:     mongo_database_indexes.txt

source env.sh

echo 'init database travel ...'
mongo $M2C_COSMOS_MONGO_CONN_STRING --ssl < mongo/mongo_indexes_travel_db.ddl
