#!/bin/bash

# Bash shell script to upload mongoexport blobs to Azure Storage with Python3.
#
# Database Name: olympics
# Generated on:  2021-10-26 19:28:57 UTC
# Generated by:  artifact_generator.py gen_python_uploads()
# Template:      blob_uploads_python.txt

source env.sh

# Uncomment, as necessary, to delete and recreate the storage container:
# python storage.py delete_blob_container olympics-raw
# sleep 10
# python storage.py create_blob_container olympics-raw
# sleep 10


echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__countries.json olympics-raw olympics__countries.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1896_summer.json olympics-raw olympics__g1896_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1900_summer.json olympics-raw olympics__g1900_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1904_summer.json olympics-raw olympics__g1904_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1906_summer.json olympics-raw olympics__g1906_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1908_summer.json olympics-raw olympics__g1908_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1912_summer.json olympics-raw olympics__g1912_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1920_summer.json olympics-raw olympics__g1920_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1924_summer.json olympics-raw olympics__g1924_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1924_winter.json olympics-raw olympics__g1924_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1928_summer.json olympics-raw olympics__g1928_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1928_winter.json olympics-raw olympics__g1928_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1932_summer.json olympics-raw olympics__g1932_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1932_winter.json olympics-raw olympics__g1932_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1936_summer.json olympics-raw olympics__g1936_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1936_winter.json olympics-raw olympics__g1936_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1948_summer.json olympics-raw olympics__g1948_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1948_winter.json olympics-raw olympics__g1948_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1952_summer.json olympics-raw olympics__g1952_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1952_winter.json olympics-raw olympics__g1952_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1956_summer.json olympics-raw olympics__g1956_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1956_winter.json olympics-raw olympics__g1956_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1960_summer.json olympics-raw olympics__g1960_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1960_winter.json olympics-raw olympics__g1960_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1964_summer.json olympics-raw olympics__g1964_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1964_winter.json olympics-raw olympics__g1964_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1968_summer.json olympics-raw olympics__g1968_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1968_winter.json olympics-raw olympics__g1968_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1972_summer.json olympics-raw olympics__g1972_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1972_winter.json olympics-raw olympics__g1972_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1976_summer.json olympics-raw olympics__g1976_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1976_winter.json olympics-raw olympics__g1976_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1980_summer.json olympics-raw olympics__g1980_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1980_winter.json olympics-raw olympics__g1980_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1984_summer.json olympics-raw olympics__g1984_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1984_winter.json olympics-raw olympics__g1984_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1988_summer.json olympics-raw olympics__g1988_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1988_winter.json olympics-raw olympics__g1988_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1992_summer.json olympics-raw olympics__g1992_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1992_winter.json olympics-raw olympics__g1992_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1994_winter.json olympics-raw olympics__g1994_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1996_summer.json olympics-raw olympics__g1996_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g1998_winter.json olympics-raw olympics__g1998_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2000_summer.json olympics-raw olympics__g2000_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2002_winter.json olympics-raw olympics__g2002_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2004_summer.json olympics-raw olympics__g2004_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2006_winter.json olympics-raw olympics__g2006_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2008_summer.json olympics-raw olympics__g2008_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2010_winter.json olympics-raw olympics__g2010_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2012_summer.json olympics-raw olympics__g2012_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2014_winter.json olympics-raw olympics__g2014_winter.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__g2016_summer.json olympics-raw olympics__g2016_summer.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/olympics/olympics__games.json olympics-raw olympics__games.json


date

echo ''
echo 'listing contents of container: olympics-raw'
python storage.py list_blob_container olympics-raw

echo 'done'