#!/bin/bash

# Bash shell script to create an autoscaled database, with containers
# in a CosmosDB/Mongo account.
#
# Database Name: olympics
# Generated on:  2021-10-26 19:28:58 UTC
# Generated by:  artifact_generator.py gen_target_cosmos_az_create()
# Template:      cosmos_db_containers_az_cli.txt

source env.sh

echo 'creating cosmos db: olympics'
az cosmosdb mongodb database create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --name olympics \
    --max-throughput 10000

echo 'creating cosmos collection: games'
az cosmosdb mongodb collection create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --database-name olympics \
    --name games \
    --shard pk
    
    # --analytical-storage-ttl

# see https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection?view=azure-cli-latest

echo 'creating cosmos collection: locations'
az cosmosdb mongodb collection create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --database-name olympics \
    --name locations \
    --shard pk
    
    # --analytical-storage-ttl

# see https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection?view=azure-cli-latest


echo 'done'