#!/bin/bash

# Bash shell script to upload mongoexport blobs to Azure Storage with Python3.
#
# Database Name: openflights
# Generated on:  2021-10-26 19:28:58 UTC
# Generated by:  artifact_generator.py gen_python_uploads()
# Template:      blob_uploads_python.txt

source env.sh

# Uncomment, as necessary, to delete and recreate the storage container:
# python storage.py delete_blob_container openflights-raw
# sleep 10
# python storage.py create_blob_container openflights-raw
# sleep 10


echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/openflights/openflights__airlines.json openflights-raw openflights__airlines.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/openflights/openflights__airports.json openflights-raw openflights__airports.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/openflights/openflights__countries.json openflights-raw openflights__countries.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/openflights/openflights__planes.json openflights-raw openflights__planes.json

echo '---'
date
python storage.py upload_blob /Users/cjoakim/github/azure-cosmos-db-mongo-migration/reference_app/data/mongoexports/openflights/openflights__routes.json openflights-raw openflights__routes.json


date

echo ''
echo 'listing contents of container: openflights-raw'
python storage.py list_blob_container openflights-raw

echo 'done'