#!/bin/bash

# Bash shell script to create an autoscaled database, with containers
# in a CosmosDB/Mongo account.
#
# Database Name: travel
# Generated on:  2021-10-26 19:28:58 UTC
# Generated by:  artifact_generator.py gen_target_cosmos_az_create()
# Template:      cosmos_db_containers_az_cli.txt

source env.sh

echo 'creating cosmos db: travel'
az cosmosdb mongodb database create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --name travel \
    --max-throughput 5000

echo 'creating cosmos collection: airlines'
az cosmosdb mongodb collection create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --database-name travel \
    --name airlines \
    --shard pk
    
    # --analytical-storage-ttl

# see https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection?view=azure-cli-latest

echo 'creating cosmos collection: airports'
az cosmosdb mongodb collection create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --database-name travel \
    --name airports \
    --shard pk
    
    # --analytical-storage-ttl

# see https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection?view=azure-cli-latest

echo 'creating cosmos collection: countries'
az cosmosdb mongodb collection create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --database-name travel \
    --name countries \
    --shard pk
    
    # --analytical-storage-ttl

# see https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection?view=azure-cli-latest

echo 'creating cosmos collection: planes'
az cosmosdb mongodb collection create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --database-name travel \
    --name planes \
    --shard pk
    
    # --analytical-storage-ttl

# see https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection?view=azure-cli-latest

echo 'creating cosmos collection: routes'
az cosmosdb mongodb collection create \
    --resource-group $M2C_RG \
    --account-name $M2C_COSMOS_MONGODB_ACCT \
    --database-name travel \
    --name routes \
    --shard pk
    
    # --analytical-storage-ttl

# see https://docs.microsoft.com/en-us/cli/azure/cosmosdb/mongodb/collection?view=azure-cli-latest


echo 'done'