version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:


# $ docker pull mongo:4.0
# $ docker-compose up -d
# $ docker ps
# $ docker volume ls
# $ mongo admin -u root -p rootpassword 
# $ docker-compose stop

# $ brew install mongodb-community
# $ brew list | grep mongo
# mongodb-community
# mongodb-database-tools
# mongosh

# References:
# - https://hub.docker.com/_/mongo/
# - https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef 
